version: '3'
services:
  amq:
    image: "vromero/activemq-artemis"
    environment:
      - TZ=Australia/Sydney
      - ARTEMIS_USERNAME=admin
      - ARTEMIS_PASSWORD=admin
    ports:
      - "8161:8161"
      - "61616:61616"
  pub:
    image: "amqdemo:latest"
    environment:
      - TZ=Australia/Sydney
      - SPRING_ARTEMIS_HOST=amq
      - SPRING_PROFILES_ACTIVE=publisher
      - CLIENT_ID=pub
      - DURABLE=true
    depends_on:
      - amq
  sub1:
    image: "amqdemo:latest"
    environment:
      - TZ=Australia/Sydney
      - SPRING_ARTEMIS_HOST=amq
      - SPRING_PROFILES_ACTIVE=subscriber1
      - CLIENT_ID=sub1
      - DURABLE=true
    depends_on:
      - amq
  sub2:
    image: "amqdemo:latest"
    environment:
      - TZ=Australia/Sydney
      - SPRING_ARTEMIS_HOST=amq
      - SPRING_PROFILES_ACTIVE=subscriber2
      - CLIENT_ID=sub2
      - DURABLE=true
    depends_on:
      - amq
